export const ayahs = [
    {arabic: "إِذَا مَسَّهُ الشَّرُّ جَزُوعًا دُعَاءًا وَإِذَا خَيْرٌ مَنُوعًا كَانَ عَنُوٓا۟", translation: "When adversity touches him, he begins to cry out for help. But when We bestow a favor upon him from Us, he says, \"I have [certainly] been given [this] because of [my] knowledge.\"", number:"41:49"},
    {arabic: "قُلْ هُوَ الرَّحْمَـٰنُ آمَنَّا بِهِ وَعَلَيْهِ تَوَكَّلْنَا ۖ فَسَتَعْلَمُونَ مَنْ هُوَ فِي ضَلَالٍ مُّبِينٍ", translation: "Say, \"He is the Most Merciful; we have believed in Him, and upon Him we have relied. And you will [come to] know who it is that is in clear error.\"", number:"67:29"},
    {arabic: "وَقَالُوا۟ لَوْلَا نُزِّلَ هَـٰذَا ٱلْقُرْءَانُ عَلَىٰ رَجُلٍۢ مِّنَ ٱلْقَرْيَتَيْنِ عَظِيمٍ", translation: "And they say, \"Why was this Qur'an not sent down upon a great person from [one of] the two cities?\"", number:"43:31"},
    {arabic: "أَهُمْ يَقْسِمُونَ رَحْمَتَ رَبِّكَ ۚ نَحْنُ قَسَمْنَا بَيْنَهُم مَّعِيشَتَهُمْ فِى ٱلْحَيَوٰةِ ٱلدُّنْيَا ۚ وَرَفَعْنَا بَعْضَهُمْ فَوْقَ بَعْضٍ دَرَجَـٰتٍ لِّيَتَّخِذَ بَعْضُهُم بَعْضًا سُخْرِيًّۭا ۗ وَرَحْمَتُ رَبِّكَ خَيْرٌۭ مِّمَّا يَجْمَعُونَ", translation: "Do they distribute the mercy of your Lord? It is We who have apportioned among them their livelihood in the life of this world and have raised some of them above others in degrees [of rank] that they may make use of one another for service. But the mercy of your Lord is better than whatever they accumulate.", number:"43:32"},
    {arabic: "وَلَوْلَآ أَن يَكُونَ ٱلنَّاسُ أُمَّةًۭ وَٟحِدَةًۭ لَّجَعَلْنَا لِمَن يَكْفُرُ بِٱلرَّحْمَـٰنِ لِبُيُوتِهِمْ سُقُفًۭا مِّن فِضَّةٍۢ وَمَعَارِجَ عَلَيْهَا يَظْهَرُونَ", translation: "And if it were not that the people would become one community [of disbelievers], We would have made for those who disbelieve in the Most Merciful - for their houses - ceilings and stairways of silver upon which to mount", number:"43:33"},
    {arabic: "وَلِبُيُوتِهِمْ أَبْوَٟبًۭا وَسُرُرًا عَلَيْهَا يَتَّكِـُٔونَ", translation: "And for their houses - doors and couches [of silver] upon which to recline", number:"43:34"},
    {arabic: "وَزُخْرُفًۭا ۚ وَإِن كُلُّ شَىْءٍۢ لَّهُم بِمَعْرُوفٍ", translation: "And gold ornament. But all that is not but the enjoyment of worldly life. And the Hereafter with your Lord is for the righteous.", number:"43:35"},
    {arabic: "وَمَن يَعْشُ عَن ذِكْرِ ٱلرَّحْمَـٰنِ نُقَيِّضْ لَهُۥ شَيْطَـَٔانًۭا فَهُوَ لَهُۥ قَرِينٌۭ", translation: "And whoever is blinded from remembrance of the Most Merciful - We appoint for him a devil, and he is to him a companion.", number:"43:36"},
]